package com.ecom.dao.example;

import com.ecom.entity.example.BaseNode3g;

public interface BaseNode3gMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_node_3g
     *
     * @mbggenerated
     */
    int insert(BaseNode3g record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_node_3g
     *
     * @mbggenerated
     */
    int insertSelective(BaseNode3g record);
}