package com.ecom.dao.example;

import com.ecom.entity.example.BaseStation;

public interface BaseStationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_station
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_station
     *
     * @mbggenerated
     */
    int insert(BaseStation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_station
     *
     * @mbggenerated
     */
    int insertSelective(BaseStation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_station
     *
     * @mbggenerated
     */
    BaseStation selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_station
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(BaseStation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_station
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(BaseStation record);
}