package com.ecom.dao.example;

import com.ecom.entity.example.BaseAlarm;

public interface BaseAlarmMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_alarm
     *
     * @mbggenerated
     */
    int insert(BaseAlarm record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_alarm
     *
     * @mbggenerated
     */
    int insertSelective(BaseAlarm record);
}