package com.ecom.dao.example;

import com.ecom.entity.example.BaseCell3g;

public interface BaseCell3gMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_cell_3g
     *
     * @mbggenerated
     */
    int insert(BaseCell3g record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_cell_3g
     *
     * @mbggenerated
     */
    int insertSelective(BaseCell3g record);
}