package com.ecom.dao.example;

import com.ecom.entity.example.BaseStation3g;

public interface BaseStation3gMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_station_3g
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_station_3g
     *
     * @mbggenerated
     */
    int insert(BaseStation3g record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_station_3g
     *
     * @mbggenerated
     */
    int insertSelective(BaseStation3g record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_station_3g
     *
     * @mbggenerated
     */
    BaseStation3g selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_station_3g
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(BaseStation3g record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_station_3g
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(BaseStation3g record);
}