package com.ecom.dao.example;

import com.ecom.entity.example.BaseCell;

public interface BaseCellMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_cell
     *
     * @mbggenerated
     */
    int insert(BaseCell record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_cell
     *
     * @mbggenerated
     */
    int insertSelective(BaseCell record);
}