package com.ecom.dao.example;

import com.ecom.entity.example.BaseRnc3g;

public interface BaseRnc3gMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_rnc_3g
     *
     * @mbggenerated
     */
    int insert(BaseRnc3g record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_rnc_3g
     *
     * @mbggenerated
     */
    int insertSelective(BaseRnc3g record);
}