package com.ecom.dao.example;

import com.ecom.entity.example.BaseTac;

public interface BaseTacMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_tac
     *
     * @mbggenerated
     */
    int insert(BaseTac record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_tac
     *
     * @mbggenerated
     */
    int insertSelective(BaseTac record);
}