package com.ecom.dao.example;

import com.ecom.entity.example.BaseNode;

public interface BaseNodeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_node
     *
     * @mbggenerated
     */
    int insert(BaseNode record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_node
     *
     * @mbggenerated
     */
    int insertSelective(BaseNode record);
}