package com.ecom.dao.example;

import com.ecom.entity.example.Counter3g;

public interface Counter3gMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table counter_3g
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table counter_3g
     *
     * @mbggenerated
     */
    int insert(Counter3g record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table counter_3g
     *
     * @mbggenerated
     */
    int insertSelective(Counter3g record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table counter_3g
     *
     * @mbggenerated
     */
    Counter3g selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table counter_3g
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Counter3g record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table counter_3g
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Counter3g record);
}