package com.ecom.dao.example;

import com.ecom.entity.example.DicAlarmType;

public interface DicAlarmTypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dic_alarm_type
     *
     * @mbggenerated
     */
    int insert(DicAlarmType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dic_alarm_type
     *
     * @mbggenerated
     */
    int insertSelective(DicAlarmType record);
}