package com.ecom.dao.example;

import com.ecom.entity.example.DicAlarmName;

public interface DicAlarmNameMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dic_alarm_name
     *
     * @mbggenerated
     */
    int insert(DicAlarmName record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dic_alarm_name
     *
     * @mbggenerated
     */
    int insertSelective(DicAlarmName record);
}