package com.ecom.dao.example;

import com.ecom.entity.example.Node3g;

public interface Node3gMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table node_3g
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table node_3g
     *
     * @mbggenerated
     */
    int insert(Node3g record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table node_3g
     *
     * @mbggenerated
     */
    int insertSelective(Node3g record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table node_3g
     *
     * @mbggenerated
     */
    Node3g selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table node_3g
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Node3g record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table node_3g
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Node3g record);
}