package com.ecom.dao.example;

import com.ecom.entity.example.QuotaThresholdCell;

public interface QuotaThresholdCellMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table quota_threshold_cell
     *
     * @mbggenerated
     */
    int insert(QuotaThresholdCell record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table quota_threshold_cell
     *
     * @mbggenerated
     */
    int insertSelective(QuotaThresholdCell record);
}