package com.ecom.dao.example;

import com.ecom.entity.example.QuotaThresholdNode3g;

public interface QuotaThresholdNode3gMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table quota_threshold_node_3g
     *
     * @mbggenerated
     */
    int insert(QuotaThresholdNode3g record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table quota_threshold_node_3g
     *
     * @mbggenerated
     */
    int insertSelective(QuotaThresholdNode3g record);
}