package com.ecom.dao.example;

import com.ecom.entity.example.QuotaThresholdTac;

public interface QuotaThresholdTacMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table quota_threshold_tac
     *
     * @mbggenerated
     */
    int insert(QuotaThresholdTac record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table quota_threshold_tac
     *
     * @mbggenerated
     */
    int insertSelective(QuotaThresholdTac record);
}