package com.ecom.dao.example;

import com.ecom.entity.example.QuotaThresholdRnc3g;

public interface QuotaThresholdRnc3gMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table quota_threshold_rnc_3g
     *
     * @mbggenerated
     */
    int insert(QuotaThresholdRnc3g record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table quota_threshold_rnc_3g
     *
     * @mbggenerated
     */
    int insertSelective(QuotaThresholdRnc3g record);
}