package com.ecom.dao.example;

import com.ecom.entity.example.QuotaThresholdNode;

public interface QuotaThresholdNodeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table quota_threshold_node
     *
     * @mbggenerated
     */
    int insert(QuotaThresholdNode record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table quota_threshold_node
     *
     * @mbggenerated
     */
    int insertSelective(QuotaThresholdNode record);
}