package com.ecom.dao.example;

import com.ecom.entity.example.QuotaThresholdCell3g;

public interface QuotaThresholdCell3gMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table quota_threshold_cell_3g
     *
     * @mbggenerated
     */
    int insert(QuotaThresholdCell3g record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table quota_threshold_cell_3g
     *
     * @mbggenerated
     */
    int insertSelective(QuotaThresholdCell3g record);
}