package com.ecom.dao.example;

import com.ecom.entity.example.Rnc3g;

public interface Rnc3gMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rnc_3g
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rnc_3g
     *
     * @mbggenerated
     */
    int insert(Rnc3g record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rnc_3g
     *
     * @mbggenerated
     */
    int insertSelective(Rnc3g record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rnc_3g
     *
     * @mbggenerated
     */
    Rnc3g selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rnc_3g
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Rnc3g record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rnc_3g
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Rnc3g record);
}