package com.ecom.dao.example;

import com.ecom.entity.example.Temp;

public interface TempMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table temp
     *
     * @mbggenerated
     */
    int insert(Temp record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table temp
     *
     * @mbggenerated
     */
    int insertSelective(Temp record);
}