package com.ecom.dao.example;

import com.ecom.entity.example.Temp3g;

public interface Temp3gMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table temp_3g
     *
     * @mbggenerated
     */
    int insert(Temp3g record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table temp_3g
     *
     * @mbggenerated
     */
    int insertSelective(Temp3g record);
}