package com.ecom.dao.example;

import com.ecom.entity.example.UserImportant;

public interface UserImportantMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_important
     *
     * @mbggenerated
     */
    int insert(UserImportant record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_important
     *
     * @mbggenerated
     */
    int insertSelective(UserImportant record);
}