package com.ecom.entity.example;

import java.io.Serializable;
import java.math.BigDecimal;

public class BaseStation3g implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_station_3g.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_station_3g.rnc
     *
     * @mbggenerated
     */
    private String rnc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_station_3g.enb_name
     *
     * @mbggenerated
     */
    private String enbName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_station_3g.rbs_id
     *
     * @mbggenerated
     */
    private Integer rbsId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_station_3g.ip
     *
     * @mbggenerated
     */
    private String ip;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_station_3g.lac
     *
     * @mbggenerated
     */
    private Integer lac;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_station_3g.latitude
     *
     * @mbggenerated
     */
    private BigDecimal latitude;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_station_3g.longitude
     *
     * @mbggenerated
     */
    private BigDecimal longitude;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table base_station_3g
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_station_3g.id
     *
     * @return the value of base_station_3g.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_station_3g.id
     *
     * @param id the value for base_station_3g.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_station_3g.rnc
     *
     * @return the value of base_station_3g.rnc
     *
     * @mbggenerated
     */
    public String getRnc() {
        return rnc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_station_3g.rnc
     *
     * @param rnc the value for base_station_3g.rnc
     *
     * @mbggenerated
     */
    public void setRnc(String rnc) {
        this.rnc = rnc == null ? null : rnc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_station_3g.enb_name
     *
     * @return the value of base_station_3g.enb_name
     *
     * @mbggenerated
     */
    public String getEnbName() {
        return enbName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_station_3g.enb_name
     *
     * @param enbName the value for base_station_3g.enb_name
     *
     * @mbggenerated
     */
    public void setEnbName(String enbName) {
        this.enbName = enbName == null ? null : enbName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_station_3g.rbs_id
     *
     * @return the value of base_station_3g.rbs_id
     *
     * @mbggenerated
     */
    public Integer getRbsId() {
        return rbsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_station_3g.rbs_id
     *
     * @param rbsId the value for base_station_3g.rbs_id
     *
     * @mbggenerated
     */
    public void setRbsId(Integer rbsId) {
        this.rbsId = rbsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_station_3g.ip
     *
     * @return the value of base_station_3g.ip
     *
     * @mbggenerated
     */
    public String getIp() {
        return ip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_station_3g.ip
     *
     * @param ip the value for base_station_3g.ip
     *
     * @mbggenerated
     */
    public void setIp(String ip) {
        this.ip = ip == null ? null : ip.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_station_3g.lac
     *
     * @return the value of base_station_3g.lac
     *
     * @mbggenerated
     */
    public Integer getLac() {
        return lac;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_station_3g.lac
     *
     * @param lac the value for base_station_3g.lac
     *
     * @mbggenerated
     */
    public void setLac(Integer lac) {
        this.lac = lac;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_station_3g.latitude
     *
     * @return the value of base_station_3g.latitude
     *
     * @mbggenerated
     */
    public BigDecimal getLatitude() {
        return latitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_station_3g.latitude
     *
     * @param latitude the value for base_station_3g.latitude
     *
     * @mbggenerated
     */
    public void setLatitude(BigDecimal latitude) {
        this.latitude = latitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_station_3g.longitude
     *
     * @return the value of base_station_3g.longitude
     *
     * @mbggenerated
     */
    public BigDecimal getLongitude() {
        return longitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_station_3g.longitude
     *
     * @param longitude the value for base_station_3g.longitude
     *
     * @mbggenerated
     */
    public void setLongitude(BigDecimal longitude) {
        this.longitude = longitude;
    }
}