package com.ecom.entity.example;

import java.io.Serializable;
import java.math.BigDecimal;

public class BaseStation implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_station.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_station.no
     *
     * @mbggenerated
     */
    private Integer no;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_station.area
     *
     * @mbggenerated
     */
    private String area;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_station.type
     *
     * @mbggenerated
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_station.format
     *
     * @mbggenerated
     */
    private String format;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_station.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_station.enb_id
     *
     * @mbggenerated
     */
    private Integer enbId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_station.enb_name
     *
     * @mbggenerated
     */
    private String enbName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_station.cell_name
     *
     * @mbggenerated
     */
    private String cellName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_station.longitude
     *
     * @mbggenerated
     */
    private BigDecimal longitude;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_station.latitude
     *
     * @mbggenerated
     */
    private BigDecimal latitude;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_station.tac
     *
     * @mbggenerated
     */
    private String tac;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_station.swversion
     *
     * @mbggenerated
     */
    private String swversion;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_station.ip
     *
     * @mbggenerated
     */
    private String ip;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_station.mme
     *
     * @mbggenerated
     */
    private String mme;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_station.license_user
     *
     * @mbggenerated
     */
    private String licenseUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table base_station
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_station.id
     *
     * @return the value of base_station.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_station.id
     *
     * @param id the value for base_station.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_station.no
     *
     * @return the value of base_station.no
     *
     * @mbggenerated
     */
    public Integer getNo() {
        return no;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_station.no
     *
     * @param no the value for base_station.no
     *
     * @mbggenerated
     */
    public void setNo(Integer no) {
        this.no = no;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_station.area
     *
     * @return the value of base_station.area
     *
     * @mbggenerated
     */
    public String getArea() {
        return area;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_station.area
     *
     * @param area the value for base_station.area
     *
     * @mbggenerated
     */
    public void setArea(String area) {
        this.area = area == null ? null : area.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_station.type
     *
     * @return the value of base_station.type
     *
     * @mbggenerated
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_station.type
     *
     * @param type the value for base_station.type
     *
     * @mbggenerated
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_station.format
     *
     * @return the value of base_station.format
     *
     * @mbggenerated
     */
    public String getFormat() {
        return format;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_station.format
     *
     * @param format the value for base_station.format
     *
     * @mbggenerated
     */
    public void setFormat(String format) {
        this.format = format == null ? null : format.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_station.name
     *
     * @return the value of base_station.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_station.name
     *
     * @param name the value for base_station.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_station.enb_id
     *
     * @return the value of base_station.enb_id
     *
     * @mbggenerated
     */
    public Integer getEnbId() {
        return enbId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_station.enb_id
     *
     * @param enbId the value for base_station.enb_id
     *
     * @mbggenerated
     */
    public void setEnbId(Integer enbId) {
        this.enbId = enbId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_station.enb_name
     *
     * @return the value of base_station.enb_name
     *
     * @mbggenerated
     */
    public String getEnbName() {
        return enbName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_station.enb_name
     *
     * @param enbName the value for base_station.enb_name
     *
     * @mbggenerated
     */
    public void setEnbName(String enbName) {
        this.enbName = enbName == null ? null : enbName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_station.cell_name
     *
     * @return the value of base_station.cell_name
     *
     * @mbggenerated
     */
    public String getCellName() {
        return cellName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_station.cell_name
     *
     * @param cellName the value for base_station.cell_name
     *
     * @mbggenerated
     */
    public void setCellName(String cellName) {
        this.cellName = cellName == null ? null : cellName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_station.longitude
     *
     * @return the value of base_station.longitude
     *
     * @mbggenerated
     */
    public BigDecimal getLongitude() {
        return longitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_station.longitude
     *
     * @param longitude the value for base_station.longitude
     *
     * @mbggenerated
     */
    public void setLongitude(BigDecimal longitude) {
        this.longitude = longitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_station.latitude
     *
     * @return the value of base_station.latitude
     *
     * @mbggenerated
     */
    public BigDecimal getLatitude() {
        return latitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_station.latitude
     *
     * @param latitude the value for base_station.latitude
     *
     * @mbggenerated
     */
    public void setLatitude(BigDecimal latitude) {
        this.latitude = latitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_station.tac
     *
     * @return the value of base_station.tac
     *
     * @mbggenerated
     */
    public String getTac() {
        return tac;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_station.tac
     *
     * @param tac the value for base_station.tac
     *
     * @mbggenerated
     */
    public void setTac(String tac) {
        this.tac = tac == null ? null : tac.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_station.swversion
     *
     * @return the value of base_station.swversion
     *
     * @mbggenerated
     */
    public String getSwversion() {
        return swversion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_station.swversion
     *
     * @param swversion the value for base_station.swversion
     *
     * @mbggenerated
     */
    public void setSwversion(String swversion) {
        this.swversion = swversion == null ? null : swversion.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_station.ip
     *
     * @return the value of base_station.ip
     *
     * @mbggenerated
     */
    public String getIp() {
        return ip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_station.ip
     *
     * @param ip the value for base_station.ip
     *
     * @mbggenerated
     */
    public void setIp(String ip) {
        this.ip = ip == null ? null : ip.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_station.mme
     *
     * @return the value of base_station.mme
     *
     * @mbggenerated
     */
    public String getMme() {
        return mme;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_station.mme
     *
     * @param mme the value for base_station.mme
     *
     * @mbggenerated
     */
    public void setMme(String mme) {
        this.mme = mme == null ? null : mme.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_station.license_user
     *
     * @return the value of base_station.license_user
     *
     * @mbggenerated
     */
    public String getLicenseUser() {
        return licenseUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_station.license_user
     *
     * @param licenseUser the value for base_station.license_user
     *
     * @mbggenerated
     */
    public void setLicenseUser(String licenseUser) {
        this.licenseUser = licenseUser == null ? null : licenseUser.trim();
    }
}