package com.ecom.entity.example;

import java.io.Serializable;
import java.util.Date;

public class Counter3g implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column counter_3g.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column counter_3g.status
     *
     * @mbggenerated
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column counter_3g.time
     *
     * @mbggenerated
     */
    private Date time;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column counter_3g.cell_name
     *
     * @mbggenerated
     */
    private String cellName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column counter_3g.Rrc_Suc
     *
     * @mbggenerated
     */
    private String rrcSuc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column counter_3g.PS_Rrc_Suc_Rate
     *
     * @mbggenerated
     */
    private String psRrcSucRate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column counter_3g.Spch_Rrc_Suc_Rate
     *
     * @mbggenerated
     */
    private String spchRrcSucRate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column counter_3g.Spch_Rab_Suc
     *
     * @mbggenerated
     */
    private String spchRabSuc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column counter_3g.PS_Rab_Succ
     *
     * @mbggenerated
     */
    private String psRabSucc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column counter_3g.SHO_Success
     *
     * @mbggenerated
     */
    private String shoSuccess;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column counter_3g.Spch_Drop
     *
     * @mbggenerated
     */
    private String spchDrop;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column counter_3g.PS_Drop
     *
     * @mbggenerated
     */
    private String psDrop;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table counter_3g
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column counter_3g.id
     *
     * @return the value of counter_3g.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column counter_3g.id
     *
     * @param id the value for counter_3g.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column counter_3g.status
     *
     * @return the value of counter_3g.status
     *
     * @mbggenerated
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column counter_3g.status
     *
     * @param status the value for counter_3g.status
     *
     * @mbggenerated
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column counter_3g.time
     *
     * @return the value of counter_3g.time
     *
     * @mbggenerated
     */
    public Date getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column counter_3g.time
     *
     * @param time the value for counter_3g.time
     *
     * @mbggenerated
     */
    public void setTime(Date time) {
        this.time = time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column counter_3g.cell_name
     *
     * @return the value of counter_3g.cell_name
     *
     * @mbggenerated
     */
    public String getCellName() {
        return cellName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column counter_3g.cell_name
     *
     * @param cellName the value for counter_3g.cell_name
     *
     * @mbggenerated
     */
    public void setCellName(String cellName) {
        this.cellName = cellName == null ? null : cellName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column counter_3g.Rrc_Suc
     *
     * @return the value of counter_3g.Rrc_Suc
     *
     * @mbggenerated
     */
    public String getRrcSuc() {
        return rrcSuc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column counter_3g.Rrc_Suc
     *
     * @param rrcSuc the value for counter_3g.Rrc_Suc
     *
     * @mbggenerated
     */
    public void setRrcSuc(String rrcSuc) {
        this.rrcSuc = rrcSuc == null ? null : rrcSuc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column counter_3g.PS_Rrc_Suc_Rate
     *
     * @return the value of counter_3g.PS_Rrc_Suc_Rate
     *
     * @mbggenerated
     */
    public String getPsRrcSucRate() {
        return psRrcSucRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column counter_3g.PS_Rrc_Suc_Rate
     *
     * @param psRrcSucRate the value for counter_3g.PS_Rrc_Suc_Rate
     *
     * @mbggenerated
     */
    public void setPsRrcSucRate(String psRrcSucRate) {
        this.psRrcSucRate = psRrcSucRate == null ? null : psRrcSucRate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column counter_3g.Spch_Rrc_Suc_Rate
     *
     * @return the value of counter_3g.Spch_Rrc_Suc_Rate
     *
     * @mbggenerated
     */
    public String getSpchRrcSucRate() {
        return spchRrcSucRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column counter_3g.Spch_Rrc_Suc_Rate
     *
     * @param spchRrcSucRate the value for counter_3g.Spch_Rrc_Suc_Rate
     *
     * @mbggenerated
     */
    public void setSpchRrcSucRate(String spchRrcSucRate) {
        this.spchRrcSucRate = spchRrcSucRate == null ? null : spchRrcSucRate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column counter_3g.Spch_Rab_Suc
     *
     * @return the value of counter_3g.Spch_Rab_Suc
     *
     * @mbggenerated
     */
    public String getSpchRabSuc() {
        return spchRabSuc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column counter_3g.Spch_Rab_Suc
     *
     * @param spchRabSuc the value for counter_3g.Spch_Rab_Suc
     *
     * @mbggenerated
     */
    public void setSpchRabSuc(String spchRabSuc) {
        this.spchRabSuc = spchRabSuc == null ? null : spchRabSuc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column counter_3g.PS_Rab_Succ
     *
     * @return the value of counter_3g.PS_Rab_Succ
     *
     * @mbggenerated
     */
    public String getPsRabSucc() {
        return psRabSucc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column counter_3g.PS_Rab_Succ
     *
     * @param psRabSucc the value for counter_3g.PS_Rab_Succ
     *
     * @mbggenerated
     */
    public void setPsRabSucc(String psRabSucc) {
        this.psRabSucc = psRabSucc == null ? null : psRabSucc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column counter_3g.SHO_Success
     *
     * @return the value of counter_3g.SHO_Success
     *
     * @mbggenerated
     */
    public String getShoSuccess() {
        return shoSuccess;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column counter_3g.SHO_Success
     *
     * @param shoSuccess the value for counter_3g.SHO_Success
     *
     * @mbggenerated
     */
    public void setShoSuccess(String shoSuccess) {
        this.shoSuccess = shoSuccess == null ? null : shoSuccess.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column counter_3g.Spch_Drop
     *
     * @return the value of counter_3g.Spch_Drop
     *
     * @mbggenerated
     */
    public String getSpchDrop() {
        return spchDrop;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column counter_3g.Spch_Drop
     *
     * @param spchDrop the value for counter_3g.Spch_Drop
     *
     * @mbggenerated
     */
    public void setSpchDrop(String spchDrop) {
        this.spchDrop = spchDrop == null ? null : spchDrop.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column counter_3g.PS_Drop
     *
     * @return the value of counter_3g.PS_Drop
     *
     * @mbggenerated
     */
    public String getPsDrop() {
        return psDrop;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column counter_3g.PS_Drop
     *
     * @param psDrop the value for counter_3g.PS_Drop
     *
     * @mbggenerated
     */
    public void setPsDrop(String psDrop) {
        this.psDrop = psDrop == null ? null : psDrop.trim();
    }
}