package com.ecom.entity.example;

import java.io.Serializable;

public class DicAlarmType implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dic_alarm_type.alarm_type
     *
     * @mbggenerated
     */
    private String alarmType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dic_alarm_type.alarm_type_name
     *
     * @mbggenerated
     */
    private String alarmTypeName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table dic_alarm_type
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dic_alarm_type.alarm_type
     *
     * @return the value of dic_alarm_type.alarm_type
     *
     * @mbggenerated
     */
    public String getAlarmType() {
        return alarmType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dic_alarm_type.alarm_type
     *
     * @param alarmType the value for dic_alarm_type.alarm_type
     *
     * @mbggenerated
     */
    public void setAlarmType(String alarmType) {
        this.alarmType = alarmType == null ? null : alarmType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dic_alarm_type.alarm_type_name
     *
     * @return the value of dic_alarm_type.alarm_type_name
     *
     * @mbggenerated
     */
    public String getAlarmTypeName() {
        return alarmTypeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dic_alarm_type.alarm_type_name
     *
     * @param alarmTypeName the value for dic_alarm_type.alarm_type_name
     *
     * @mbggenerated
     */
    public void setAlarmTypeName(String alarmTypeName) {
        this.alarmTypeName = alarmTypeName == null ? null : alarmTypeName.trim();
    }
}