package com.ecom.entity.example;

import java.io.Serializable;
import java.util.Date;

public class Temp3g implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column temp_3g.rnc_name
     *
     * @mbggenerated
     */
    private String rncName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column temp_3g.cell_name
     *
     * @mbggenerated
     */
    private String cellName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column temp_3g.iur_link_name
     *
     * @mbggenerated
     */
    private String iurLinkName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column temp_3g.time
     *
     * @mbggenerated
     */
    private Date time;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column temp_3g.pm_No_Iu_Sig_Establish_Success_Cs
     *
     * @mbggenerated
     */
    private String pmNoIuSigEstablishSuccessCs;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column temp_3g.pm_No_Iu_Sig_Establish_Attempt_Cs
     *
     * @mbggenerated
     */
    private String pmNoIuSigEstablishAttemptCs;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column temp_3g.pm_No_Iu_Sig_Establish_Success_Ps
     *
     * @mbggenerated
     */
    private String pmNoIuSigEstablishSuccessPs;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column temp_3g.pm_No_Iu_Sig_Establish_Attempt_Ps
     *
     * @mbggenerated
     */
    private String pmNoIuSigEstablishAttemptPs;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column temp_3g.pm_Tot_No_Rrc_Connect_Req_Success
     *
     * @mbggenerated
     */
    private String pmTotNoRrcConnectReqSuccess;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column temp_3g.pm_Tot_No_Rrc_Connect_Req
     *
     * @mbggenerated
     */
    private String pmTotNoRrcConnectReq;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column temp_3g.pm_No_Load_Sharing_Rrc_Conn
     *
     * @mbggenerated
     */
    private String pmNoLoadSharingRrcConn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column temp_3g.pm_Tot_No_Rrc_Connect_Req_Ps_Succ
     *
     * @mbggenerated
     */
    private String pmTotNoRrcConnectReqPsSucc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column temp_3g.pm_Tot_No_Rrc_Connect_Req_Ps
     *
     * @mbggenerated
     */
    private String pmTotNoRrcConnectReqPs;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column temp_3g.pm_No_Load_Sharing_Rrc_Conn_Ps
     *
     * @mbggenerated
     */
    private String pmNoLoadSharingRrcConnPs;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column temp_3g.pm_Tot_No_Rrc_Connect_Req_Cs_Succ
     *
     * @mbggenerated
     */
    private String pmTotNoRrcConnectReqCsSucc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column temp_3g.pm_Tot_No_Rrc_Connect_Req_Cs
     *
     * @mbggenerated
     */
    private String pmTotNoRrcConnectReqCs;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column temp_3g.pm_No_Load_Sharing_Rrc_Conn_Cs
     *
     * @mbggenerated
     */
    private String pmNoLoadSharingRrcConnCs;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column temp_3g.pm_No_Rab_Establish_Success_Speech
     *
     * @mbggenerated
     */
    private String pmNoRabEstablishSuccessSpeech;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column temp_3g.pm_No_Rab_Establish_Attempt_Speech
     *
     * @mbggenerated
     */
    private String pmNoRabEstablishAttemptSpeech;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column temp_3g.pm_No_Rab_Establish_Success_Packet_Interactive
     *
     * @mbggenerated
     */
    private String pmNoRabEstablishSuccessPacketInteractive;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column temp_3g.pm_No_Rab_Establish_Attempt_Packet_Interactive
     *
     * @mbggenerated
     */
    private String pmNoRabEstablishAttemptPacketInteractive;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column temp_3g.pm_No_Times_Rl_Add_To_Act_Set
     *
     * @mbggenerated
     */
    private String pmNoTimesRlAddToActSet;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column temp_3g.pm_No_Times_Cell_Fail_Add_To_Act_Set
     *
     * @mbggenerated
     */
    private String pmNoTimesCellFailAddToActSet;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column temp_3g.pm_No_System_Rab_Release_Speech
     *
     * @mbggenerated
     */
    private String pmNoSystemRabReleaseSpeech;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column temp_3g.pm_No_Normal_Rab_Release_Speech
     *
     * @mbggenerated
     */
    private String pmNoNormalRabReleaseSpeech;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column temp_3g.pm_No_System_Rab_Release_Packet
     *
     * @mbggenerated
     */
    private String pmNoSystemRabReleasePacket;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column temp_3g.pm_No_System_Rab_Release_Packet_Ura
     *
     * @mbggenerated
     */
    private String pmNoSystemRabReleasePacketUra;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column temp_3g.pm_Ch_Switch_Attempt_Fach_Ura
     *
     * @mbggenerated
     */
    private String pmChSwitchAttemptFachUra;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column temp_3g.pm_Ch_Switch_Succ_Fach_Ura
     *
     * @mbggenerated
     */
    private String pmChSwitchSuccFachUra;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column temp_3g.pm_Ch_Switch_Attempt_Dch_Ura
     *
     * @mbggenerated
     */
    private String pmChSwitchAttemptDchUra;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column temp_3g.pm_Ch_Switch_Succ_Dch_Ura
     *
     * @mbggenerated
     */
    private String pmChSwitchSuccDchUra;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column temp_3g.pm_Ch_Switch_Attempt_Hs_Ura
     *
     * @mbggenerated
     */
    private String pmChSwitchAttemptHsUra;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column temp_3g.pm_Ch_Switch_Succ_Hs_Ura
     *
     * @mbggenerated
     */
    private String pmChSwitchSuccHsUra;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column temp_3g.pm_No_Normal_Rab_Release_Packet
     *
     * @mbggenerated
     */
    private String pmNoNormalRabReleasePacket;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column temp_3g.pm_No_Normal_Rab_Release_Packet_Ura
     *
     * @mbggenerated
     */
    private String pmNoNormalRabReleasePacketUra;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table temp_3g
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column temp_3g.rnc_name
     *
     * @return the value of temp_3g.rnc_name
     *
     * @mbggenerated
     */
    public String getRncName() {
        return rncName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column temp_3g.rnc_name
     *
     * @param rncName the value for temp_3g.rnc_name
     *
     * @mbggenerated
     */
    public void setRncName(String rncName) {
        this.rncName = rncName == null ? null : rncName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column temp_3g.cell_name
     *
     * @return the value of temp_3g.cell_name
     *
     * @mbggenerated
     */
    public String getCellName() {
        return cellName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column temp_3g.cell_name
     *
     * @param cellName the value for temp_3g.cell_name
     *
     * @mbggenerated
     */
    public void setCellName(String cellName) {
        this.cellName = cellName == null ? null : cellName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column temp_3g.iur_link_name
     *
     * @return the value of temp_3g.iur_link_name
     *
     * @mbggenerated
     */
    public String getIurLinkName() {
        return iurLinkName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column temp_3g.iur_link_name
     *
     * @param iurLinkName the value for temp_3g.iur_link_name
     *
     * @mbggenerated
     */
    public void setIurLinkName(String iurLinkName) {
        this.iurLinkName = iurLinkName == null ? null : iurLinkName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column temp_3g.time
     *
     * @return the value of temp_3g.time
     *
     * @mbggenerated
     */
    public Date getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column temp_3g.time
     *
     * @param time the value for temp_3g.time
     *
     * @mbggenerated
     */
    public void setTime(Date time) {
        this.time = time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column temp_3g.pm_No_Iu_Sig_Establish_Success_Cs
     *
     * @return the value of temp_3g.pm_No_Iu_Sig_Establish_Success_Cs
     *
     * @mbggenerated
     */
    public String getPmNoIuSigEstablishSuccessCs() {
        return pmNoIuSigEstablishSuccessCs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column temp_3g.pm_No_Iu_Sig_Establish_Success_Cs
     *
     * @param pmNoIuSigEstablishSuccessCs the value for temp_3g.pm_No_Iu_Sig_Establish_Success_Cs
     *
     * @mbggenerated
     */
    public void setPmNoIuSigEstablishSuccessCs(String pmNoIuSigEstablishSuccessCs) {
        this.pmNoIuSigEstablishSuccessCs = pmNoIuSigEstablishSuccessCs == null ? null : pmNoIuSigEstablishSuccessCs.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column temp_3g.pm_No_Iu_Sig_Establish_Attempt_Cs
     *
     * @return the value of temp_3g.pm_No_Iu_Sig_Establish_Attempt_Cs
     *
     * @mbggenerated
     */
    public String getPmNoIuSigEstablishAttemptCs() {
        return pmNoIuSigEstablishAttemptCs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column temp_3g.pm_No_Iu_Sig_Establish_Attempt_Cs
     *
     * @param pmNoIuSigEstablishAttemptCs the value for temp_3g.pm_No_Iu_Sig_Establish_Attempt_Cs
     *
     * @mbggenerated
     */
    public void setPmNoIuSigEstablishAttemptCs(String pmNoIuSigEstablishAttemptCs) {
        this.pmNoIuSigEstablishAttemptCs = pmNoIuSigEstablishAttemptCs == null ? null : pmNoIuSigEstablishAttemptCs.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column temp_3g.pm_No_Iu_Sig_Establish_Success_Ps
     *
     * @return the value of temp_3g.pm_No_Iu_Sig_Establish_Success_Ps
     *
     * @mbggenerated
     */
    public String getPmNoIuSigEstablishSuccessPs() {
        return pmNoIuSigEstablishSuccessPs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column temp_3g.pm_No_Iu_Sig_Establish_Success_Ps
     *
     * @param pmNoIuSigEstablishSuccessPs the value for temp_3g.pm_No_Iu_Sig_Establish_Success_Ps
     *
     * @mbggenerated
     */
    public void setPmNoIuSigEstablishSuccessPs(String pmNoIuSigEstablishSuccessPs) {
        this.pmNoIuSigEstablishSuccessPs = pmNoIuSigEstablishSuccessPs == null ? null : pmNoIuSigEstablishSuccessPs.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column temp_3g.pm_No_Iu_Sig_Establish_Attempt_Ps
     *
     * @return the value of temp_3g.pm_No_Iu_Sig_Establish_Attempt_Ps
     *
     * @mbggenerated
     */
    public String getPmNoIuSigEstablishAttemptPs() {
        return pmNoIuSigEstablishAttemptPs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column temp_3g.pm_No_Iu_Sig_Establish_Attempt_Ps
     *
     * @param pmNoIuSigEstablishAttemptPs the value for temp_3g.pm_No_Iu_Sig_Establish_Attempt_Ps
     *
     * @mbggenerated
     */
    public void setPmNoIuSigEstablishAttemptPs(String pmNoIuSigEstablishAttemptPs) {
        this.pmNoIuSigEstablishAttemptPs = pmNoIuSigEstablishAttemptPs == null ? null : pmNoIuSigEstablishAttemptPs.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column temp_3g.pm_Tot_No_Rrc_Connect_Req_Success
     *
     * @return the value of temp_3g.pm_Tot_No_Rrc_Connect_Req_Success
     *
     * @mbggenerated
     */
    public String getPmTotNoRrcConnectReqSuccess() {
        return pmTotNoRrcConnectReqSuccess;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column temp_3g.pm_Tot_No_Rrc_Connect_Req_Success
     *
     * @param pmTotNoRrcConnectReqSuccess the value for temp_3g.pm_Tot_No_Rrc_Connect_Req_Success
     *
     * @mbggenerated
     */
    public void setPmTotNoRrcConnectReqSuccess(String pmTotNoRrcConnectReqSuccess) {
        this.pmTotNoRrcConnectReqSuccess = pmTotNoRrcConnectReqSuccess == null ? null : pmTotNoRrcConnectReqSuccess.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column temp_3g.pm_Tot_No_Rrc_Connect_Req
     *
     * @return the value of temp_3g.pm_Tot_No_Rrc_Connect_Req
     *
     * @mbggenerated
     */
    public String getPmTotNoRrcConnectReq() {
        return pmTotNoRrcConnectReq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column temp_3g.pm_Tot_No_Rrc_Connect_Req
     *
     * @param pmTotNoRrcConnectReq the value for temp_3g.pm_Tot_No_Rrc_Connect_Req
     *
     * @mbggenerated
     */
    public void setPmTotNoRrcConnectReq(String pmTotNoRrcConnectReq) {
        this.pmTotNoRrcConnectReq = pmTotNoRrcConnectReq == null ? null : pmTotNoRrcConnectReq.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column temp_3g.pm_No_Load_Sharing_Rrc_Conn
     *
     * @return the value of temp_3g.pm_No_Load_Sharing_Rrc_Conn
     *
     * @mbggenerated
     */
    public String getPmNoLoadSharingRrcConn() {
        return pmNoLoadSharingRrcConn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column temp_3g.pm_No_Load_Sharing_Rrc_Conn
     *
     * @param pmNoLoadSharingRrcConn the value for temp_3g.pm_No_Load_Sharing_Rrc_Conn
     *
     * @mbggenerated
     */
    public void setPmNoLoadSharingRrcConn(String pmNoLoadSharingRrcConn) {
        this.pmNoLoadSharingRrcConn = pmNoLoadSharingRrcConn == null ? null : pmNoLoadSharingRrcConn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column temp_3g.pm_Tot_No_Rrc_Connect_Req_Ps_Succ
     *
     * @return the value of temp_3g.pm_Tot_No_Rrc_Connect_Req_Ps_Succ
     *
     * @mbggenerated
     */
    public String getPmTotNoRrcConnectReqPsSucc() {
        return pmTotNoRrcConnectReqPsSucc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column temp_3g.pm_Tot_No_Rrc_Connect_Req_Ps_Succ
     *
     * @param pmTotNoRrcConnectReqPsSucc the value for temp_3g.pm_Tot_No_Rrc_Connect_Req_Ps_Succ
     *
     * @mbggenerated
     */
    public void setPmTotNoRrcConnectReqPsSucc(String pmTotNoRrcConnectReqPsSucc) {
        this.pmTotNoRrcConnectReqPsSucc = pmTotNoRrcConnectReqPsSucc == null ? null : pmTotNoRrcConnectReqPsSucc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column temp_3g.pm_Tot_No_Rrc_Connect_Req_Ps
     *
     * @return the value of temp_3g.pm_Tot_No_Rrc_Connect_Req_Ps
     *
     * @mbggenerated
     */
    public String getPmTotNoRrcConnectReqPs() {
        return pmTotNoRrcConnectReqPs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column temp_3g.pm_Tot_No_Rrc_Connect_Req_Ps
     *
     * @param pmTotNoRrcConnectReqPs the value for temp_3g.pm_Tot_No_Rrc_Connect_Req_Ps
     *
     * @mbggenerated
     */
    public void setPmTotNoRrcConnectReqPs(String pmTotNoRrcConnectReqPs) {
        this.pmTotNoRrcConnectReqPs = pmTotNoRrcConnectReqPs == null ? null : pmTotNoRrcConnectReqPs.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column temp_3g.pm_No_Load_Sharing_Rrc_Conn_Ps
     *
     * @return the value of temp_3g.pm_No_Load_Sharing_Rrc_Conn_Ps
     *
     * @mbggenerated
     */
    public String getPmNoLoadSharingRrcConnPs() {
        return pmNoLoadSharingRrcConnPs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column temp_3g.pm_No_Load_Sharing_Rrc_Conn_Ps
     *
     * @param pmNoLoadSharingRrcConnPs the value for temp_3g.pm_No_Load_Sharing_Rrc_Conn_Ps
     *
     * @mbggenerated
     */
    public void setPmNoLoadSharingRrcConnPs(String pmNoLoadSharingRrcConnPs) {
        this.pmNoLoadSharingRrcConnPs = pmNoLoadSharingRrcConnPs == null ? null : pmNoLoadSharingRrcConnPs.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column temp_3g.pm_Tot_No_Rrc_Connect_Req_Cs_Succ
     *
     * @return the value of temp_3g.pm_Tot_No_Rrc_Connect_Req_Cs_Succ
     *
     * @mbggenerated
     */
    public String getPmTotNoRrcConnectReqCsSucc() {
        return pmTotNoRrcConnectReqCsSucc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column temp_3g.pm_Tot_No_Rrc_Connect_Req_Cs_Succ
     *
     * @param pmTotNoRrcConnectReqCsSucc the value for temp_3g.pm_Tot_No_Rrc_Connect_Req_Cs_Succ
     *
     * @mbggenerated
     */
    public void setPmTotNoRrcConnectReqCsSucc(String pmTotNoRrcConnectReqCsSucc) {
        this.pmTotNoRrcConnectReqCsSucc = pmTotNoRrcConnectReqCsSucc == null ? null : pmTotNoRrcConnectReqCsSucc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column temp_3g.pm_Tot_No_Rrc_Connect_Req_Cs
     *
     * @return the value of temp_3g.pm_Tot_No_Rrc_Connect_Req_Cs
     *
     * @mbggenerated
     */
    public String getPmTotNoRrcConnectReqCs() {
        return pmTotNoRrcConnectReqCs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column temp_3g.pm_Tot_No_Rrc_Connect_Req_Cs
     *
     * @param pmTotNoRrcConnectReqCs the value for temp_3g.pm_Tot_No_Rrc_Connect_Req_Cs
     *
     * @mbggenerated
     */
    public void setPmTotNoRrcConnectReqCs(String pmTotNoRrcConnectReqCs) {
        this.pmTotNoRrcConnectReqCs = pmTotNoRrcConnectReqCs == null ? null : pmTotNoRrcConnectReqCs.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column temp_3g.pm_No_Load_Sharing_Rrc_Conn_Cs
     *
     * @return the value of temp_3g.pm_No_Load_Sharing_Rrc_Conn_Cs
     *
     * @mbggenerated
     */
    public String getPmNoLoadSharingRrcConnCs() {
        return pmNoLoadSharingRrcConnCs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column temp_3g.pm_No_Load_Sharing_Rrc_Conn_Cs
     *
     * @param pmNoLoadSharingRrcConnCs the value for temp_3g.pm_No_Load_Sharing_Rrc_Conn_Cs
     *
     * @mbggenerated
     */
    public void setPmNoLoadSharingRrcConnCs(String pmNoLoadSharingRrcConnCs) {
        this.pmNoLoadSharingRrcConnCs = pmNoLoadSharingRrcConnCs == null ? null : pmNoLoadSharingRrcConnCs.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column temp_3g.pm_No_Rab_Establish_Success_Speech
     *
     * @return the value of temp_3g.pm_No_Rab_Establish_Success_Speech
     *
     * @mbggenerated
     */
    public String getPmNoRabEstablishSuccessSpeech() {
        return pmNoRabEstablishSuccessSpeech;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column temp_3g.pm_No_Rab_Establish_Success_Speech
     *
     * @param pmNoRabEstablishSuccessSpeech the value for temp_3g.pm_No_Rab_Establish_Success_Speech
     *
     * @mbggenerated
     */
    public void setPmNoRabEstablishSuccessSpeech(String pmNoRabEstablishSuccessSpeech) {
        this.pmNoRabEstablishSuccessSpeech = pmNoRabEstablishSuccessSpeech == null ? null : pmNoRabEstablishSuccessSpeech.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column temp_3g.pm_No_Rab_Establish_Attempt_Speech
     *
     * @return the value of temp_3g.pm_No_Rab_Establish_Attempt_Speech
     *
     * @mbggenerated
     */
    public String getPmNoRabEstablishAttemptSpeech() {
        return pmNoRabEstablishAttemptSpeech;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column temp_3g.pm_No_Rab_Establish_Attempt_Speech
     *
     * @param pmNoRabEstablishAttemptSpeech the value for temp_3g.pm_No_Rab_Establish_Attempt_Speech
     *
     * @mbggenerated
     */
    public void setPmNoRabEstablishAttemptSpeech(String pmNoRabEstablishAttemptSpeech) {
        this.pmNoRabEstablishAttemptSpeech = pmNoRabEstablishAttemptSpeech == null ? null : pmNoRabEstablishAttemptSpeech.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column temp_3g.pm_No_Rab_Establish_Success_Packet_Interactive
     *
     * @return the value of temp_3g.pm_No_Rab_Establish_Success_Packet_Interactive
     *
     * @mbggenerated
     */
    public String getPmNoRabEstablishSuccessPacketInteractive() {
        return pmNoRabEstablishSuccessPacketInteractive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column temp_3g.pm_No_Rab_Establish_Success_Packet_Interactive
     *
     * @param pmNoRabEstablishSuccessPacketInteractive the value for temp_3g.pm_No_Rab_Establish_Success_Packet_Interactive
     *
     * @mbggenerated
     */
    public void setPmNoRabEstablishSuccessPacketInteractive(String pmNoRabEstablishSuccessPacketInteractive) {
        this.pmNoRabEstablishSuccessPacketInteractive = pmNoRabEstablishSuccessPacketInteractive == null ? null : pmNoRabEstablishSuccessPacketInteractive.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column temp_3g.pm_No_Rab_Establish_Attempt_Packet_Interactive
     *
     * @return the value of temp_3g.pm_No_Rab_Establish_Attempt_Packet_Interactive
     *
     * @mbggenerated
     */
    public String getPmNoRabEstablishAttemptPacketInteractive() {
        return pmNoRabEstablishAttemptPacketInteractive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column temp_3g.pm_No_Rab_Establish_Attempt_Packet_Interactive
     *
     * @param pmNoRabEstablishAttemptPacketInteractive the value for temp_3g.pm_No_Rab_Establish_Attempt_Packet_Interactive
     *
     * @mbggenerated
     */
    public void setPmNoRabEstablishAttemptPacketInteractive(String pmNoRabEstablishAttemptPacketInteractive) {
        this.pmNoRabEstablishAttemptPacketInteractive = pmNoRabEstablishAttemptPacketInteractive == null ? null : pmNoRabEstablishAttemptPacketInteractive.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column temp_3g.pm_No_Times_Rl_Add_To_Act_Set
     *
     * @return the value of temp_3g.pm_No_Times_Rl_Add_To_Act_Set
     *
     * @mbggenerated
     */
    public String getPmNoTimesRlAddToActSet() {
        return pmNoTimesRlAddToActSet;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column temp_3g.pm_No_Times_Rl_Add_To_Act_Set
     *
     * @param pmNoTimesRlAddToActSet the value for temp_3g.pm_No_Times_Rl_Add_To_Act_Set
     *
     * @mbggenerated
     */
    public void setPmNoTimesRlAddToActSet(String pmNoTimesRlAddToActSet) {
        this.pmNoTimesRlAddToActSet = pmNoTimesRlAddToActSet == null ? null : pmNoTimesRlAddToActSet.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column temp_3g.pm_No_Times_Cell_Fail_Add_To_Act_Set
     *
     * @return the value of temp_3g.pm_No_Times_Cell_Fail_Add_To_Act_Set
     *
     * @mbggenerated
     */
    public String getPmNoTimesCellFailAddToActSet() {
        return pmNoTimesCellFailAddToActSet;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column temp_3g.pm_No_Times_Cell_Fail_Add_To_Act_Set
     *
     * @param pmNoTimesCellFailAddToActSet the value for temp_3g.pm_No_Times_Cell_Fail_Add_To_Act_Set
     *
     * @mbggenerated
     */
    public void setPmNoTimesCellFailAddToActSet(String pmNoTimesCellFailAddToActSet) {
        this.pmNoTimesCellFailAddToActSet = pmNoTimesCellFailAddToActSet == null ? null : pmNoTimesCellFailAddToActSet.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column temp_3g.pm_No_System_Rab_Release_Speech
     *
     * @return the value of temp_3g.pm_No_System_Rab_Release_Speech
     *
     * @mbggenerated
     */
    public String getPmNoSystemRabReleaseSpeech() {
        return pmNoSystemRabReleaseSpeech;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column temp_3g.pm_No_System_Rab_Release_Speech
     *
     * @param pmNoSystemRabReleaseSpeech the value for temp_3g.pm_No_System_Rab_Release_Speech
     *
     * @mbggenerated
     */
    public void setPmNoSystemRabReleaseSpeech(String pmNoSystemRabReleaseSpeech) {
        this.pmNoSystemRabReleaseSpeech = pmNoSystemRabReleaseSpeech == null ? null : pmNoSystemRabReleaseSpeech.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column temp_3g.pm_No_Normal_Rab_Release_Speech
     *
     * @return the value of temp_3g.pm_No_Normal_Rab_Release_Speech
     *
     * @mbggenerated
     */
    public String getPmNoNormalRabReleaseSpeech() {
        return pmNoNormalRabReleaseSpeech;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column temp_3g.pm_No_Normal_Rab_Release_Speech
     *
     * @param pmNoNormalRabReleaseSpeech the value for temp_3g.pm_No_Normal_Rab_Release_Speech
     *
     * @mbggenerated
     */
    public void setPmNoNormalRabReleaseSpeech(String pmNoNormalRabReleaseSpeech) {
        this.pmNoNormalRabReleaseSpeech = pmNoNormalRabReleaseSpeech == null ? null : pmNoNormalRabReleaseSpeech.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column temp_3g.pm_No_System_Rab_Release_Packet
     *
     * @return the value of temp_3g.pm_No_System_Rab_Release_Packet
     *
     * @mbggenerated
     */
    public String getPmNoSystemRabReleasePacket() {
        return pmNoSystemRabReleasePacket;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column temp_3g.pm_No_System_Rab_Release_Packet
     *
     * @param pmNoSystemRabReleasePacket the value for temp_3g.pm_No_System_Rab_Release_Packet
     *
     * @mbggenerated
     */
    public void setPmNoSystemRabReleasePacket(String pmNoSystemRabReleasePacket) {
        this.pmNoSystemRabReleasePacket = pmNoSystemRabReleasePacket == null ? null : pmNoSystemRabReleasePacket.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column temp_3g.pm_No_System_Rab_Release_Packet_Ura
     *
     * @return the value of temp_3g.pm_No_System_Rab_Release_Packet_Ura
     *
     * @mbggenerated
     */
    public String getPmNoSystemRabReleasePacketUra() {
        return pmNoSystemRabReleasePacketUra;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column temp_3g.pm_No_System_Rab_Release_Packet_Ura
     *
     * @param pmNoSystemRabReleasePacketUra the value for temp_3g.pm_No_System_Rab_Release_Packet_Ura
     *
     * @mbggenerated
     */
    public void setPmNoSystemRabReleasePacketUra(String pmNoSystemRabReleasePacketUra) {
        this.pmNoSystemRabReleasePacketUra = pmNoSystemRabReleasePacketUra == null ? null : pmNoSystemRabReleasePacketUra.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column temp_3g.pm_Ch_Switch_Attempt_Fach_Ura
     *
     * @return the value of temp_3g.pm_Ch_Switch_Attempt_Fach_Ura
     *
     * @mbggenerated
     */
    public String getPmChSwitchAttemptFachUra() {
        return pmChSwitchAttemptFachUra;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column temp_3g.pm_Ch_Switch_Attempt_Fach_Ura
     *
     * @param pmChSwitchAttemptFachUra the value for temp_3g.pm_Ch_Switch_Attempt_Fach_Ura
     *
     * @mbggenerated
     */
    public void setPmChSwitchAttemptFachUra(String pmChSwitchAttemptFachUra) {
        this.pmChSwitchAttemptFachUra = pmChSwitchAttemptFachUra == null ? null : pmChSwitchAttemptFachUra.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column temp_3g.pm_Ch_Switch_Succ_Fach_Ura
     *
     * @return the value of temp_3g.pm_Ch_Switch_Succ_Fach_Ura
     *
     * @mbggenerated
     */
    public String getPmChSwitchSuccFachUra() {
        return pmChSwitchSuccFachUra;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column temp_3g.pm_Ch_Switch_Succ_Fach_Ura
     *
     * @param pmChSwitchSuccFachUra the value for temp_3g.pm_Ch_Switch_Succ_Fach_Ura
     *
     * @mbggenerated
     */
    public void setPmChSwitchSuccFachUra(String pmChSwitchSuccFachUra) {
        this.pmChSwitchSuccFachUra = pmChSwitchSuccFachUra == null ? null : pmChSwitchSuccFachUra.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column temp_3g.pm_Ch_Switch_Attempt_Dch_Ura
     *
     * @return the value of temp_3g.pm_Ch_Switch_Attempt_Dch_Ura
     *
     * @mbggenerated
     */
    public String getPmChSwitchAttemptDchUra() {
        return pmChSwitchAttemptDchUra;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column temp_3g.pm_Ch_Switch_Attempt_Dch_Ura
     *
     * @param pmChSwitchAttemptDchUra the value for temp_3g.pm_Ch_Switch_Attempt_Dch_Ura
     *
     * @mbggenerated
     */
    public void setPmChSwitchAttemptDchUra(String pmChSwitchAttemptDchUra) {
        this.pmChSwitchAttemptDchUra = pmChSwitchAttemptDchUra == null ? null : pmChSwitchAttemptDchUra.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column temp_3g.pm_Ch_Switch_Succ_Dch_Ura
     *
     * @return the value of temp_3g.pm_Ch_Switch_Succ_Dch_Ura
     *
     * @mbggenerated
     */
    public String getPmChSwitchSuccDchUra() {
        return pmChSwitchSuccDchUra;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column temp_3g.pm_Ch_Switch_Succ_Dch_Ura
     *
     * @param pmChSwitchSuccDchUra the value for temp_3g.pm_Ch_Switch_Succ_Dch_Ura
     *
     * @mbggenerated
     */
    public void setPmChSwitchSuccDchUra(String pmChSwitchSuccDchUra) {
        this.pmChSwitchSuccDchUra = pmChSwitchSuccDchUra == null ? null : pmChSwitchSuccDchUra.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column temp_3g.pm_Ch_Switch_Attempt_Hs_Ura
     *
     * @return the value of temp_3g.pm_Ch_Switch_Attempt_Hs_Ura
     *
     * @mbggenerated
     */
    public String getPmChSwitchAttemptHsUra() {
        return pmChSwitchAttemptHsUra;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column temp_3g.pm_Ch_Switch_Attempt_Hs_Ura
     *
     * @param pmChSwitchAttemptHsUra the value for temp_3g.pm_Ch_Switch_Attempt_Hs_Ura
     *
     * @mbggenerated
     */
    public void setPmChSwitchAttemptHsUra(String pmChSwitchAttemptHsUra) {
        this.pmChSwitchAttemptHsUra = pmChSwitchAttemptHsUra == null ? null : pmChSwitchAttemptHsUra.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column temp_3g.pm_Ch_Switch_Succ_Hs_Ura
     *
     * @return the value of temp_3g.pm_Ch_Switch_Succ_Hs_Ura
     *
     * @mbggenerated
     */
    public String getPmChSwitchSuccHsUra() {
        return pmChSwitchSuccHsUra;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column temp_3g.pm_Ch_Switch_Succ_Hs_Ura
     *
     * @param pmChSwitchSuccHsUra the value for temp_3g.pm_Ch_Switch_Succ_Hs_Ura
     *
     * @mbggenerated
     */
    public void setPmChSwitchSuccHsUra(String pmChSwitchSuccHsUra) {
        this.pmChSwitchSuccHsUra = pmChSwitchSuccHsUra == null ? null : pmChSwitchSuccHsUra.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column temp_3g.pm_No_Normal_Rab_Release_Packet
     *
     * @return the value of temp_3g.pm_No_Normal_Rab_Release_Packet
     *
     * @mbggenerated
     */
    public String getPmNoNormalRabReleasePacket() {
        return pmNoNormalRabReleasePacket;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column temp_3g.pm_No_Normal_Rab_Release_Packet
     *
     * @param pmNoNormalRabReleasePacket the value for temp_3g.pm_No_Normal_Rab_Release_Packet
     *
     * @mbggenerated
     */
    public void setPmNoNormalRabReleasePacket(String pmNoNormalRabReleasePacket) {
        this.pmNoNormalRabReleasePacket = pmNoNormalRabReleasePacket == null ? null : pmNoNormalRabReleasePacket.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column temp_3g.pm_No_Normal_Rab_Release_Packet_Ura
     *
     * @return the value of temp_3g.pm_No_Normal_Rab_Release_Packet_Ura
     *
     * @mbggenerated
     */
    public String getPmNoNormalRabReleasePacketUra() {
        return pmNoNormalRabReleasePacketUra;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column temp_3g.pm_No_Normal_Rab_Release_Packet_Ura
     *
     * @param pmNoNormalRabReleasePacketUra the value for temp_3g.pm_No_Normal_Rab_Release_Packet_Ura
     *
     * @mbggenerated
     */
    public void setPmNoNormalRabReleasePacketUra(String pmNoNormalRabReleasePacketUra) {
        this.pmNoNormalRabReleasePacketUra = pmNoNormalRabReleasePacketUra == null ? null : pmNoNormalRabReleasePacketUra.trim();
    }
}