package com.ecom.entity.example;

import java.io.Serializable;

public class Temp implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column temp.cell_name
     *
     * @mbggenerated
     */
    private String cellName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column temp.EUtranCellFDD_pmRrcConnEstabAtt
     *
     * @mbggenerated
     */
    private Integer eutrancellfddPmrrcconnestabatt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column temp.EUtranCellTDD_pmRrcConnEstabAtt
     *
     * @mbggenerated
     */
    private Integer eutrancelltddPmrrcconnestabatt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column temp.EUtranCellFDD_pmRrcConnEstabAttReatt
     *
     * @mbggenerated
     */
    private Integer eutrancellfddPmrrcconnestabattreatt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column temp.EUtranCellTDD_pmRrcConnEstabAttReatt
     *
     * @mbggenerated
     */
    private Integer eutrancelltddPmrrcconnestabattreatt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column temp.EUtranCellFDD_pmRrcConnEstabSucc
     *
     * @mbggenerated
     */
    private Integer eutrancellfddPmrrcconnestabsucc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column temp.EUtranCellTDD_pmRrcConnEstabSucc
     *
     * @mbggenerated
     */
    private Integer eutrancelltddPmrrcconnestabsucc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column temp.EUtranCellFDD_pmS1SigConnEstabAtt
     *
     * @mbggenerated
     */
    private Integer eutrancellfddPms1sigconnestabatt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column temp.EUtranCellTDD_pmS1SigConnEstabAtt
     *
     * @mbggenerated
     */
    private Integer eutrancelltddPms1sigconnestabatt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column temp.EUtranCellFDD_pmS1SigConnEstabSucc
     *
     * @mbggenerated
     */
    private Integer eutrancellfddPms1sigconnestabsucc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column temp.EUtranCellTDD_pmS1SigConnEstabSucc
     *
     * @mbggenerated
     */
    private Integer eutrancelltddPms1sigconnestabsucc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column temp.EUtranCellFDD_pmErabEstabAttInit
     *
     * @mbggenerated
     */
    private Integer eutrancellfddPmerabestabattinit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column temp.EUtranCellTDD_pmErabEstabAttInit
     *
     * @mbggenerated
     */
    private Integer eutrancelltddPmerabestabattinit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column temp.EUtranCellFDD_pmErabEstabAttAdded
     *
     * @mbggenerated
     */
    private Integer eutrancellfddPmerabestabattadded;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column temp.EUtranCellTDD_pmErabEstabAttAdded
     *
     * @mbggenerated
     */
    private Integer eutrancelltddPmerabestabattadded;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column temp.EUtranCellFDD_pmErabEstabSuccInit
     *
     * @mbggenerated
     */
    private Integer eutrancellfddPmerabestabsuccinit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column temp.EUtranCellTDD_pmErabEstabSuccInit
     *
     * @mbggenerated
     */
    private Integer eutrancelltddPmerabestabsuccinit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column temp.EUtranCellFDD_pmErabEstabSuccAdded
     *
     * @mbggenerated
     */
    private Integer eutrancellfddPmerabestabsuccadded;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column temp.EUtranCellTDD_pmErabEstabSuccAdded
     *
     * @mbggenerated
     */
    private Integer eutrancelltddPmerabestabsuccadded;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column temp.EUtranCellFDD_pmPagReceived
     *
     * @mbggenerated
     */
    private Integer eutrancellfddPmpagreceived;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column temp.EUtranCellTDD_pmPagReceived
     *
     * @mbggenerated
     */
    private Integer eutrancelltddPmpagreceived;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column temp.EUtranCellFDD_pmPagDiscarded
     *
     * @mbggenerated
     */
    private Integer eutrancellfddPmpagdiscarded;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column temp.EUtranCellTDD_pmPagDiscarded
     *
     * @mbggenerated
     */
    private Integer eutrancelltddPmpagdiscarded;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column temp.EUtranCellFDD_pmErabRelAbnormalEnbAct
     *
     * @mbggenerated
     */
    private Integer eutrancellfddPmerabrelabnormalenbact;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column temp.EUtranCellTDD_pmErabRelAbnormalEnbAct
     *
     * @mbggenerated
     */
    private Integer eutrancelltddPmerabrelabnormalenbact;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column temp.EUtranCellFDD_pmErabRelMmeAct
     *
     * @mbggenerated
     */
    private Integer eutrancellfddPmerabrelmmeact;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column temp.EUtranCellTDD_pmErabRelMmeAct
     *
     * @mbggenerated
     */
    private Integer eutrancelltddPmerabrelmmeact;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column temp.EUtranCellRelation_pmHoPrepAttLteInterF
     *
     * @mbggenerated
     */
    private Integer eutrancellrelationPmhoprepattlteinterf;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column temp.EUtranCellRelation_pmHoPrepAttLteIntraF
     *
     * @mbggenerated
     */
    private Integer eutrancellrelationPmhoprepattlteintraf;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column temp.EUtranCellRelation_pmHoExeSuccLteInterF
     *
     * @mbggenerated
     */
    private Integer eutrancellrelationPmhoexesucclteinterf;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column temp.EUtranCellRelation_pmHoExeSuccLteIntraF
     *
     * @mbggenerated
     */
    private Integer eutrancellrelationPmhoexesucclteintraf;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column temp.pmPrbUsedDlFirstTrans
     *
     * @mbggenerated
     */
    private Integer pmprbuseddlfirsttrans;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column temp.pmPrbUsedDlBcch
     *
     * @mbggenerated
     */
    private Integer pmprbuseddlbcch;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column temp.pmPrbUsedDlDtch
     *
     * @mbggenerated
     */
    private Integer pmprbuseddldtch;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column temp.pmPrbUsedDlPcch
     *
     * @mbggenerated
     */
    private Integer pmprbuseddlpcch;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column temp.pmPrbUsedDlSrbFirstTrans
     *
     * @mbggenerated
     */
    private Integer pmprbuseddlsrbfirsttrans;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column temp.pmPrbUsedDlReTrans
     *
     * @mbggenerated
     */
    private Integer pmprbuseddlretrans;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column temp.pmPrbUsedUlDtch
     *
     * @mbggenerated
     */
    private Integer pmprbuseduldtch;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column temp.pmPrbUsedUlSrb
     *
     * @mbggenerated
     */
    private Integer pmprbusedulsrb;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column temp.pmPdcpVolDlDrb
     *
     * @mbggenerated
     */
    private Integer pmpdcpvoldldrb;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column temp.pmPdcpVolUlDrb
     *
     * @mbggenerated
     */
    private Integer pmpdcpvoluldrb;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column temp.pmUeThpTimeDl
     *
     * @mbggenerated
     */
    private Integer pmuethptimedl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column temp.pmPdcpVolDlDrbLastTTI
     *
     * @mbggenerated
     */
    private Integer pmpdcpvoldldrblasttti;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column temp.pmUeThpTimeUl
     *
     * @mbggenerated
     */
    private Integer pmuethptimeul;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column temp.pmUeThpVolUl
     *
     * @mbggenerated
     */
    private Integer pmuethpvolul;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column temp.pmSessionTimeUe
     *
     * @mbggenerated
     */
    private Integer pmsessiontimeue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column temp.pmSessionTimeDrb
     *
     * @mbggenerated
     */
    private Integer pmsessiontimedrb;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column temp.pmActiveUeDlSum
     *
     * @mbggenerated
     */
    private Integer pmactiveuedlsum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column temp.pmActiveUeUlSum
     *
     * @mbggenerated
     */
    private Integer pmactiveueulsum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column temp.pmErabLevSamp
     *
     * @mbggenerated
     */
    private Integer pmerablevsamp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column temp.pmCellDowntimeAuto
     *
     * @mbggenerated
     */
    private Integer pmcelldowntimeauto;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table temp
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column temp.cell_name
     *
     * @return the value of temp.cell_name
     *
     * @mbggenerated
     */
    public String getCellName() {
        return cellName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column temp.cell_name
     *
     * @param cellName the value for temp.cell_name
     *
     * @mbggenerated
     */
    public void setCellName(String cellName) {
        this.cellName = cellName == null ? null : cellName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column temp.EUtranCellFDD_pmRrcConnEstabAtt
     *
     * @return the value of temp.EUtranCellFDD_pmRrcConnEstabAtt
     *
     * @mbggenerated
     */
    public Integer getEutrancellfddPmrrcconnestabatt() {
        return eutrancellfddPmrrcconnestabatt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column temp.EUtranCellFDD_pmRrcConnEstabAtt
     *
     * @param eutrancellfddPmrrcconnestabatt the value for temp.EUtranCellFDD_pmRrcConnEstabAtt
     *
     * @mbggenerated
     */
    public void setEutrancellfddPmrrcconnestabatt(Integer eutrancellfddPmrrcconnestabatt) {
        this.eutrancellfddPmrrcconnestabatt = eutrancellfddPmrrcconnestabatt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column temp.EUtranCellTDD_pmRrcConnEstabAtt
     *
     * @return the value of temp.EUtranCellTDD_pmRrcConnEstabAtt
     *
     * @mbggenerated
     */
    public Integer getEutrancelltddPmrrcconnestabatt() {
        return eutrancelltddPmrrcconnestabatt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column temp.EUtranCellTDD_pmRrcConnEstabAtt
     *
     * @param eutrancelltddPmrrcconnestabatt the value for temp.EUtranCellTDD_pmRrcConnEstabAtt
     *
     * @mbggenerated
     */
    public void setEutrancelltddPmrrcconnestabatt(Integer eutrancelltddPmrrcconnestabatt) {
        this.eutrancelltddPmrrcconnestabatt = eutrancelltddPmrrcconnestabatt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column temp.EUtranCellFDD_pmRrcConnEstabAttReatt
     *
     * @return the value of temp.EUtranCellFDD_pmRrcConnEstabAttReatt
     *
     * @mbggenerated
     */
    public Integer getEutrancellfddPmrrcconnestabattreatt() {
        return eutrancellfddPmrrcconnestabattreatt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column temp.EUtranCellFDD_pmRrcConnEstabAttReatt
     *
     * @param eutrancellfddPmrrcconnestabattreatt the value for temp.EUtranCellFDD_pmRrcConnEstabAttReatt
     *
     * @mbggenerated
     */
    public void setEutrancellfddPmrrcconnestabattreatt(Integer eutrancellfddPmrrcconnestabattreatt) {
        this.eutrancellfddPmrrcconnestabattreatt = eutrancellfddPmrrcconnestabattreatt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column temp.EUtranCellTDD_pmRrcConnEstabAttReatt
     *
     * @return the value of temp.EUtranCellTDD_pmRrcConnEstabAttReatt
     *
     * @mbggenerated
     */
    public Integer getEutrancelltddPmrrcconnestabattreatt() {
        return eutrancelltddPmrrcconnestabattreatt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column temp.EUtranCellTDD_pmRrcConnEstabAttReatt
     *
     * @param eutrancelltddPmrrcconnestabattreatt the value for temp.EUtranCellTDD_pmRrcConnEstabAttReatt
     *
     * @mbggenerated
     */
    public void setEutrancelltddPmrrcconnestabattreatt(Integer eutrancelltddPmrrcconnestabattreatt) {
        this.eutrancelltddPmrrcconnestabattreatt = eutrancelltddPmrrcconnestabattreatt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column temp.EUtranCellFDD_pmRrcConnEstabSucc
     *
     * @return the value of temp.EUtranCellFDD_pmRrcConnEstabSucc
     *
     * @mbggenerated
     */
    public Integer getEutrancellfddPmrrcconnestabsucc() {
        return eutrancellfddPmrrcconnestabsucc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column temp.EUtranCellFDD_pmRrcConnEstabSucc
     *
     * @param eutrancellfddPmrrcconnestabsucc the value for temp.EUtranCellFDD_pmRrcConnEstabSucc
     *
     * @mbggenerated
     */
    public void setEutrancellfddPmrrcconnestabsucc(Integer eutrancellfddPmrrcconnestabsucc) {
        this.eutrancellfddPmrrcconnestabsucc = eutrancellfddPmrrcconnestabsucc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column temp.EUtranCellTDD_pmRrcConnEstabSucc
     *
     * @return the value of temp.EUtranCellTDD_pmRrcConnEstabSucc
     *
     * @mbggenerated
     */
    public Integer getEutrancelltddPmrrcconnestabsucc() {
        return eutrancelltddPmrrcconnestabsucc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column temp.EUtranCellTDD_pmRrcConnEstabSucc
     *
     * @param eutrancelltddPmrrcconnestabsucc the value for temp.EUtranCellTDD_pmRrcConnEstabSucc
     *
     * @mbggenerated
     */
    public void setEutrancelltddPmrrcconnestabsucc(Integer eutrancelltddPmrrcconnestabsucc) {
        this.eutrancelltddPmrrcconnestabsucc = eutrancelltddPmrrcconnestabsucc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column temp.EUtranCellFDD_pmS1SigConnEstabAtt
     *
     * @return the value of temp.EUtranCellFDD_pmS1SigConnEstabAtt
     *
     * @mbggenerated
     */
    public Integer getEutrancellfddPms1sigconnestabatt() {
        return eutrancellfddPms1sigconnestabatt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column temp.EUtranCellFDD_pmS1SigConnEstabAtt
     *
     * @param eutrancellfddPms1sigconnestabatt the value for temp.EUtranCellFDD_pmS1SigConnEstabAtt
     *
     * @mbggenerated
     */
    public void setEutrancellfddPms1sigconnestabatt(Integer eutrancellfddPms1sigconnestabatt) {
        this.eutrancellfddPms1sigconnestabatt = eutrancellfddPms1sigconnestabatt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column temp.EUtranCellTDD_pmS1SigConnEstabAtt
     *
     * @return the value of temp.EUtranCellTDD_pmS1SigConnEstabAtt
     *
     * @mbggenerated
     */
    public Integer getEutrancelltddPms1sigconnestabatt() {
        return eutrancelltddPms1sigconnestabatt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column temp.EUtranCellTDD_pmS1SigConnEstabAtt
     *
     * @param eutrancelltddPms1sigconnestabatt the value for temp.EUtranCellTDD_pmS1SigConnEstabAtt
     *
     * @mbggenerated
     */
    public void setEutrancelltddPms1sigconnestabatt(Integer eutrancelltddPms1sigconnestabatt) {
        this.eutrancelltddPms1sigconnestabatt = eutrancelltddPms1sigconnestabatt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column temp.EUtranCellFDD_pmS1SigConnEstabSucc
     *
     * @return the value of temp.EUtranCellFDD_pmS1SigConnEstabSucc
     *
     * @mbggenerated
     */
    public Integer getEutrancellfddPms1sigconnestabsucc() {
        return eutrancellfddPms1sigconnestabsucc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column temp.EUtranCellFDD_pmS1SigConnEstabSucc
     *
     * @param eutrancellfddPms1sigconnestabsucc the value for temp.EUtranCellFDD_pmS1SigConnEstabSucc
     *
     * @mbggenerated
     */
    public void setEutrancellfddPms1sigconnestabsucc(Integer eutrancellfddPms1sigconnestabsucc) {
        this.eutrancellfddPms1sigconnestabsucc = eutrancellfddPms1sigconnestabsucc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column temp.EUtranCellTDD_pmS1SigConnEstabSucc
     *
     * @return the value of temp.EUtranCellTDD_pmS1SigConnEstabSucc
     *
     * @mbggenerated
     */
    public Integer getEutrancelltddPms1sigconnestabsucc() {
        return eutrancelltddPms1sigconnestabsucc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column temp.EUtranCellTDD_pmS1SigConnEstabSucc
     *
     * @param eutrancelltddPms1sigconnestabsucc the value for temp.EUtranCellTDD_pmS1SigConnEstabSucc
     *
     * @mbggenerated
     */
    public void setEutrancelltddPms1sigconnestabsucc(Integer eutrancelltddPms1sigconnestabsucc) {
        this.eutrancelltddPms1sigconnestabsucc = eutrancelltddPms1sigconnestabsucc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column temp.EUtranCellFDD_pmErabEstabAttInit
     *
     * @return the value of temp.EUtranCellFDD_pmErabEstabAttInit
     *
     * @mbggenerated
     */
    public Integer getEutrancellfddPmerabestabattinit() {
        return eutrancellfddPmerabestabattinit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column temp.EUtranCellFDD_pmErabEstabAttInit
     *
     * @param eutrancellfddPmerabestabattinit the value for temp.EUtranCellFDD_pmErabEstabAttInit
     *
     * @mbggenerated
     */
    public void setEutrancellfddPmerabestabattinit(Integer eutrancellfddPmerabestabattinit) {
        this.eutrancellfddPmerabestabattinit = eutrancellfddPmerabestabattinit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column temp.EUtranCellTDD_pmErabEstabAttInit
     *
     * @return the value of temp.EUtranCellTDD_pmErabEstabAttInit
     *
     * @mbggenerated
     */
    public Integer getEutrancelltddPmerabestabattinit() {
        return eutrancelltddPmerabestabattinit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column temp.EUtranCellTDD_pmErabEstabAttInit
     *
     * @param eutrancelltddPmerabestabattinit the value for temp.EUtranCellTDD_pmErabEstabAttInit
     *
     * @mbggenerated
     */
    public void setEutrancelltddPmerabestabattinit(Integer eutrancelltddPmerabestabattinit) {
        this.eutrancelltddPmerabestabattinit = eutrancelltddPmerabestabattinit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column temp.EUtranCellFDD_pmErabEstabAttAdded
     *
     * @return the value of temp.EUtranCellFDD_pmErabEstabAttAdded
     *
     * @mbggenerated
     */
    public Integer getEutrancellfddPmerabestabattadded() {
        return eutrancellfddPmerabestabattadded;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column temp.EUtranCellFDD_pmErabEstabAttAdded
     *
     * @param eutrancellfddPmerabestabattadded the value for temp.EUtranCellFDD_pmErabEstabAttAdded
     *
     * @mbggenerated
     */
    public void setEutrancellfddPmerabestabattadded(Integer eutrancellfddPmerabestabattadded) {
        this.eutrancellfddPmerabestabattadded = eutrancellfddPmerabestabattadded;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column temp.EUtranCellTDD_pmErabEstabAttAdded
     *
     * @return the value of temp.EUtranCellTDD_pmErabEstabAttAdded
     *
     * @mbggenerated
     */
    public Integer getEutrancelltddPmerabestabattadded() {
        return eutrancelltddPmerabestabattadded;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column temp.EUtranCellTDD_pmErabEstabAttAdded
     *
     * @param eutrancelltddPmerabestabattadded the value for temp.EUtranCellTDD_pmErabEstabAttAdded
     *
     * @mbggenerated
     */
    public void setEutrancelltddPmerabestabattadded(Integer eutrancelltddPmerabestabattadded) {
        this.eutrancelltddPmerabestabattadded = eutrancelltddPmerabestabattadded;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column temp.EUtranCellFDD_pmErabEstabSuccInit
     *
     * @return the value of temp.EUtranCellFDD_pmErabEstabSuccInit
     *
     * @mbggenerated
     */
    public Integer getEutrancellfddPmerabestabsuccinit() {
        return eutrancellfddPmerabestabsuccinit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column temp.EUtranCellFDD_pmErabEstabSuccInit
     *
     * @param eutrancellfddPmerabestabsuccinit the value for temp.EUtranCellFDD_pmErabEstabSuccInit
     *
     * @mbggenerated
     */
    public void setEutrancellfddPmerabestabsuccinit(Integer eutrancellfddPmerabestabsuccinit) {
        this.eutrancellfddPmerabestabsuccinit = eutrancellfddPmerabestabsuccinit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column temp.EUtranCellTDD_pmErabEstabSuccInit
     *
     * @return the value of temp.EUtranCellTDD_pmErabEstabSuccInit
     *
     * @mbggenerated
     */
    public Integer getEutrancelltddPmerabestabsuccinit() {
        return eutrancelltddPmerabestabsuccinit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column temp.EUtranCellTDD_pmErabEstabSuccInit
     *
     * @param eutrancelltddPmerabestabsuccinit the value for temp.EUtranCellTDD_pmErabEstabSuccInit
     *
     * @mbggenerated
     */
    public void setEutrancelltddPmerabestabsuccinit(Integer eutrancelltddPmerabestabsuccinit) {
        this.eutrancelltddPmerabestabsuccinit = eutrancelltddPmerabestabsuccinit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column temp.EUtranCellFDD_pmErabEstabSuccAdded
     *
     * @return the value of temp.EUtranCellFDD_pmErabEstabSuccAdded
     *
     * @mbggenerated
     */
    public Integer getEutrancellfddPmerabestabsuccadded() {
        return eutrancellfddPmerabestabsuccadded;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column temp.EUtranCellFDD_pmErabEstabSuccAdded
     *
     * @param eutrancellfddPmerabestabsuccadded the value for temp.EUtranCellFDD_pmErabEstabSuccAdded
     *
     * @mbggenerated
     */
    public void setEutrancellfddPmerabestabsuccadded(Integer eutrancellfddPmerabestabsuccadded) {
        this.eutrancellfddPmerabestabsuccadded = eutrancellfddPmerabestabsuccadded;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column temp.EUtranCellTDD_pmErabEstabSuccAdded
     *
     * @return the value of temp.EUtranCellTDD_pmErabEstabSuccAdded
     *
     * @mbggenerated
     */
    public Integer getEutrancelltddPmerabestabsuccadded() {
        return eutrancelltddPmerabestabsuccadded;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column temp.EUtranCellTDD_pmErabEstabSuccAdded
     *
     * @param eutrancelltddPmerabestabsuccadded the value for temp.EUtranCellTDD_pmErabEstabSuccAdded
     *
     * @mbggenerated
     */
    public void setEutrancelltddPmerabestabsuccadded(Integer eutrancelltddPmerabestabsuccadded) {
        this.eutrancelltddPmerabestabsuccadded = eutrancelltddPmerabestabsuccadded;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column temp.EUtranCellFDD_pmPagReceived
     *
     * @return the value of temp.EUtranCellFDD_pmPagReceived
     *
     * @mbggenerated
     */
    public Integer getEutrancellfddPmpagreceived() {
        return eutrancellfddPmpagreceived;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column temp.EUtranCellFDD_pmPagReceived
     *
     * @param eutrancellfddPmpagreceived the value for temp.EUtranCellFDD_pmPagReceived
     *
     * @mbggenerated
     */
    public void setEutrancellfddPmpagreceived(Integer eutrancellfddPmpagreceived) {
        this.eutrancellfddPmpagreceived = eutrancellfddPmpagreceived;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column temp.EUtranCellTDD_pmPagReceived
     *
     * @return the value of temp.EUtranCellTDD_pmPagReceived
     *
     * @mbggenerated
     */
    public Integer getEutrancelltddPmpagreceived() {
        return eutrancelltddPmpagreceived;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column temp.EUtranCellTDD_pmPagReceived
     *
     * @param eutrancelltddPmpagreceived the value for temp.EUtranCellTDD_pmPagReceived
     *
     * @mbggenerated
     */
    public void setEutrancelltddPmpagreceived(Integer eutrancelltddPmpagreceived) {
        this.eutrancelltddPmpagreceived = eutrancelltddPmpagreceived;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column temp.EUtranCellFDD_pmPagDiscarded
     *
     * @return the value of temp.EUtranCellFDD_pmPagDiscarded
     *
     * @mbggenerated
     */
    public Integer getEutrancellfddPmpagdiscarded() {
        return eutrancellfddPmpagdiscarded;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column temp.EUtranCellFDD_pmPagDiscarded
     *
     * @param eutrancellfddPmpagdiscarded the value for temp.EUtranCellFDD_pmPagDiscarded
     *
     * @mbggenerated
     */
    public void setEutrancellfddPmpagdiscarded(Integer eutrancellfddPmpagdiscarded) {
        this.eutrancellfddPmpagdiscarded = eutrancellfddPmpagdiscarded;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column temp.EUtranCellTDD_pmPagDiscarded
     *
     * @return the value of temp.EUtranCellTDD_pmPagDiscarded
     *
     * @mbggenerated
     */
    public Integer getEutrancelltddPmpagdiscarded() {
        return eutrancelltddPmpagdiscarded;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column temp.EUtranCellTDD_pmPagDiscarded
     *
     * @param eutrancelltddPmpagdiscarded the value for temp.EUtranCellTDD_pmPagDiscarded
     *
     * @mbggenerated
     */
    public void setEutrancelltddPmpagdiscarded(Integer eutrancelltddPmpagdiscarded) {
        this.eutrancelltddPmpagdiscarded = eutrancelltddPmpagdiscarded;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column temp.EUtranCellFDD_pmErabRelAbnormalEnbAct
     *
     * @return the value of temp.EUtranCellFDD_pmErabRelAbnormalEnbAct
     *
     * @mbggenerated
     */
    public Integer getEutrancellfddPmerabrelabnormalenbact() {
        return eutrancellfddPmerabrelabnormalenbact;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column temp.EUtranCellFDD_pmErabRelAbnormalEnbAct
     *
     * @param eutrancellfddPmerabrelabnormalenbact the value for temp.EUtranCellFDD_pmErabRelAbnormalEnbAct
     *
     * @mbggenerated
     */
    public void setEutrancellfddPmerabrelabnormalenbact(Integer eutrancellfddPmerabrelabnormalenbact) {
        this.eutrancellfddPmerabrelabnormalenbact = eutrancellfddPmerabrelabnormalenbact;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column temp.EUtranCellTDD_pmErabRelAbnormalEnbAct
     *
     * @return the value of temp.EUtranCellTDD_pmErabRelAbnormalEnbAct
     *
     * @mbggenerated
     */
    public Integer getEutrancelltddPmerabrelabnormalenbact() {
        return eutrancelltddPmerabrelabnormalenbact;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column temp.EUtranCellTDD_pmErabRelAbnormalEnbAct
     *
     * @param eutrancelltddPmerabrelabnormalenbact the value for temp.EUtranCellTDD_pmErabRelAbnormalEnbAct
     *
     * @mbggenerated
     */
    public void setEutrancelltddPmerabrelabnormalenbact(Integer eutrancelltddPmerabrelabnormalenbact) {
        this.eutrancelltddPmerabrelabnormalenbact = eutrancelltddPmerabrelabnormalenbact;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column temp.EUtranCellFDD_pmErabRelMmeAct
     *
     * @return the value of temp.EUtranCellFDD_pmErabRelMmeAct
     *
     * @mbggenerated
     */
    public Integer getEutrancellfddPmerabrelmmeact() {
        return eutrancellfddPmerabrelmmeact;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column temp.EUtranCellFDD_pmErabRelMmeAct
     *
     * @param eutrancellfddPmerabrelmmeact the value for temp.EUtranCellFDD_pmErabRelMmeAct
     *
     * @mbggenerated
     */
    public void setEutrancellfddPmerabrelmmeact(Integer eutrancellfddPmerabrelmmeact) {
        this.eutrancellfddPmerabrelmmeact = eutrancellfddPmerabrelmmeact;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column temp.EUtranCellTDD_pmErabRelMmeAct
     *
     * @return the value of temp.EUtranCellTDD_pmErabRelMmeAct
     *
     * @mbggenerated
     */
    public Integer getEutrancelltddPmerabrelmmeact() {
        return eutrancelltddPmerabrelmmeact;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column temp.EUtranCellTDD_pmErabRelMmeAct
     *
     * @param eutrancelltddPmerabrelmmeact the value for temp.EUtranCellTDD_pmErabRelMmeAct
     *
     * @mbggenerated
     */
    public void setEutrancelltddPmerabrelmmeact(Integer eutrancelltddPmerabrelmmeact) {
        this.eutrancelltddPmerabrelmmeact = eutrancelltddPmerabrelmmeact;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column temp.EUtranCellRelation_pmHoPrepAttLteInterF
     *
     * @return the value of temp.EUtranCellRelation_pmHoPrepAttLteInterF
     *
     * @mbggenerated
     */
    public Integer getEutrancellrelationPmhoprepattlteinterf() {
        return eutrancellrelationPmhoprepattlteinterf;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column temp.EUtranCellRelation_pmHoPrepAttLteInterF
     *
     * @param eutrancellrelationPmhoprepattlteinterf the value for temp.EUtranCellRelation_pmHoPrepAttLteInterF
     *
     * @mbggenerated
     */
    public void setEutrancellrelationPmhoprepattlteinterf(Integer eutrancellrelationPmhoprepattlteinterf) {
        this.eutrancellrelationPmhoprepattlteinterf = eutrancellrelationPmhoprepattlteinterf;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column temp.EUtranCellRelation_pmHoPrepAttLteIntraF
     *
     * @return the value of temp.EUtranCellRelation_pmHoPrepAttLteIntraF
     *
     * @mbggenerated
     */
    public Integer getEutrancellrelationPmhoprepattlteintraf() {
        return eutrancellrelationPmhoprepattlteintraf;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column temp.EUtranCellRelation_pmHoPrepAttLteIntraF
     *
     * @param eutrancellrelationPmhoprepattlteintraf the value for temp.EUtranCellRelation_pmHoPrepAttLteIntraF
     *
     * @mbggenerated
     */
    public void setEutrancellrelationPmhoprepattlteintraf(Integer eutrancellrelationPmhoprepattlteintraf) {
        this.eutrancellrelationPmhoprepattlteintraf = eutrancellrelationPmhoprepattlteintraf;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column temp.EUtranCellRelation_pmHoExeSuccLteInterF
     *
     * @return the value of temp.EUtranCellRelation_pmHoExeSuccLteInterF
     *
     * @mbggenerated
     */
    public Integer getEutrancellrelationPmhoexesucclteinterf() {
        return eutrancellrelationPmhoexesucclteinterf;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column temp.EUtranCellRelation_pmHoExeSuccLteInterF
     *
     * @param eutrancellrelationPmhoexesucclteinterf the value for temp.EUtranCellRelation_pmHoExeSuccLteInterF
     *
     * @mbggenerated
     */
    public void setEutrancellrelationPmhoexesucclteinterf(Integer eutrancellrelationPmhoexesucclteinterf) {
        this.eutrancellrelationPmhoexesucclteinterf = eutrancellrelationPmhoexesucclteinterf;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column temp.EUtranCellRelation_pmHoExeSuccLteIntraF
     *
     * @return the value of temp.EUtranCellRelation_pmHoExeSuccLteIntraF
     *
     * @mbggenerated
     */
    public Integer getEutrancellrelationPmhoexesucclteintraf() {
        return eutrancellrelationPmhoexesucclteintraf;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column temp.EUtranCellRelation_pmHoExeSuccLteIntraF
     *
     * @param eutrancellrelationPmhoexesucclteintraf the value for temp.EUtranCellRelation_pmHoExeSuccLteIntraF
     *
     * @mbggenerated
     */
    public void setEutrancellrelationPmhoexesucclteintraf(Integer eutrancellrelationPmhoexesucclteintraf) {
        this.eutrancellrelationPmhoexesucclteintraf = eutrancellrelationPmhoexesucclteintraf;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column temp.pmPrbUsedDlFirstTrans
     *
     * @return the value of temp.pmPrbUsedDlFirstTrans
     *
     * @mbggenerated
     */
    public Integer getPmprbuseddlfirsttrans() {
        return pmprbuseddlfirsttrans;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column temp.pmPrbUsedDlFirstTrans
     *
     * @param pmprbuseddlfirsttrans the value for temp.pmPrbUsedDlFirstTrans
     *
     * @mbggenerated
     */
    public void setPmprbuseddlfirsttrans(Integer pmprbuseddlfirsttrans) {
        this.pmprbuseddlfirsttrans = pmprbuseddlfirsttrans;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column temp.pmPrbUsedDlBcch
     *
     * @return the value of temp.pmPrbUsedDlBcch
     *
     * @mbggenerated
     */
    public Integer getPmprbuseddlbcch() {
        return pmprbuseddlbcch;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column temp.pmPrbUsedDlBcch
     *
     * @param pmprbuseddlbcch the value for temp.pmPrbUsedDlBcch
     *
     * @mbggenerated
     */
    public void setPmprbuseddlbcch(Integer pmprbuseddlbcch) {
        this.pmprbuseddlbcch = pmprbuseddlbcch;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column temp.pmPrbUsedDlDtch
     *
     * @return the value of temp.pmPrbUsedDlDtch
     *
     * @mbggenerated
     */
    public Integer getPmprbuseddldtch() {
        return pmprbuseddldtch;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column temp.pmPrbUsedDlDtch
     *
     * @param pmprbuseddldtch the value for temp.pmPrbUsedDlDtch
     *
     * @mbggenerated
     */
    public void setPmprbuseddldtch(Integer pmprbuseddldtch) {
        this.pmprbuseddldtch = pmprbuseddldtch;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column temp.pmPrbUsedDlPcch
     *
     * @return the value of temp.pmPrbUsedDlPcch
     *
     * @mbggenerated
     */
    public Integer getPmprbuseddlpcch() {
        return pmprbuseddlpcch;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column temp.pmPrbUsedDlPcch
     *
     * @param pmprbuseddlpcch the value for temp.pmPrbUsedDlPcch
     *
     * @mbggenerated
     */
    public void setPmprbuseddlpcch(Integer pmprbuseddlpcch) {
        this.pmprbuseddlpcch = pmprbuseddlpcch;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column temp.pmPrbUsedDlSrbFirstTrans
     *
     * @return the value of temp.pmPrbUsedDlSrbFirstTrans
     *
     * @mbggenerated
     */
    public Integer getPmprbuseddlsrbfirsttrans() {
        return pmprbuseddlsrbfirsttrans;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column temp.pmPrbUsedDlSrbFirstTrans
     *
     * @param pmprbuseddlsrbfirsttrans the value for temp.pmPrbUsedDlSrbFirstTrans
     *
     * @mbggenerated
     */
    public void setPmprbuseddlsrbfirsttrans(Integer pmprbuseddlsrbfirsttrans) {
        this.pmprbuseddlsrbfirsttrans = pmprbuseddlsrbfirsttrans;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column temp.pmPrbUsedDlReTrans
     *
     * @return the value of temp.pmPrbUsedDlReTrans
     *
     * @mbggenerated
     */
    public Integer getPmprbuseddlretrans() {
        return pmprbuseddlretrans;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column temp.pmPrbUsedDlReTrans
     *
     * @param pmprbuseddlretrans the value for temp.pmPrbUsedDlReTrans
     *
     * @mbggenerated
     */
    public void setPmprbuseddlretrans(Integer pmprbuseddlretrans) {
        this.pmprbuseddlretrans = pmprbuseddlretrans;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column temp.pmPrbUsedUlDtch
     *
     * @return the value of temp.pmPrbUsedUlDtch
     *
     * @mbggenerated
     */
    public Integer getPmprbuseduldtch() {
        return pmprbuseduldtch;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column temp.pmPrbUsedUlDtch
     *
     * @param pmprbuseduldtch the value for temp.pmPrbUsedUlDtch
     *
     * @mbggenerated
     */
    public void setPmprbuseduldtch(Integer pmprbuseduldtch) {
        this.pmprbuseduldtch = pmprbuseduldtch;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column temp.pmPrbUsedUlSrb
     *
     * @return the value of temp.pmPrbUsedUlSrb
     *
     * @mbggenerated
     */
    public Integer getPmprbusedulsrb() {
        return pmprbusedulsrb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column temp.pmPrbUsedUlSrb
     *
     * @param pmprbusedulsrb the value for temp.pmPrbUsedUlSrb
     *
     * @mbggenerated
     */
    public void setPmprbusedulsrb(Integer pmprbusedulsrb) {
        this.pmprbusedulsrb = pmprbusedulsrb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column temp.pmPdcpVolDlDrb
     *
     * @return the value of temp.pmPdcpVolDlDrb
     *
     * @mbggenerated
     */
    public Integer getPmpdcpvoldldrb() {
        return pmpdcpvoldldrb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column temp.pmPdcpVolDlDrb
     *
     * @param pmpdcpvoldldrb the value for temp.pmPdcpVolDlDrb
     *
     * @mbggenerated
     */
    public void setPmpdcpvoldldrb(Integer pmpdcpvoldldrb) {
        this.pmpdcpvoldldrb = pmpdcpvoldldrb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column temp.pmPdcpVolUlDrb
     *
     * @return the value of temp.pmPdcpVolUlDrb
     *
     * @mbggenerated
     */
    public Integer getPmpdcpvoluldrb() {
        return pmpdcpvoluldrb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column temp.pmPdcpVolUlDrb
     *
     * @param pmpdcpvoluldrb the value for temp.pmPdcpVolUlDrb
     *
     * @mbggenerated
     */
    public void setPmpdcpvoluldrb(Integer pmpdcpvoluldrb) {
        this.pmpdcpvoluldrb = pmpdcpvoluldrb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column temp.pmUeThpTimeDl
     *
     * @return the value of temp.pmUeThpTimeDl
     *
     * @mbggenerated
     */
    public Integer getPmuethptimedl() {
        return pmuethptimedl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column temp.pmUeThpTimeDl
     *
     * @param pmuethptimedl the value for temp.pmUeThpTimeDl
     *
     * @mbggenerated
     */
    public void setPmuethptimedl(Integer pmuethptimedl) {
        this.pmuethptimedl = pmuethptimedl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column temp.pmPdcpVolDlDrbLastTTI
     *
     * @return the value of temp.pmPdcpVolDlDrbLastTTI
     *
     * @mbggenerated
     */
    public Integer getPmpdcpvoldldrblasttti() {
        return pmpdcpvoldldrblasttti;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column temp.pmPdcpVolDlDrbLastTTI
     *
     * @param pmpdcpvoldldrblasttti the value for temp.pmPdcpVolDlDrbLastTTI
     *
     * @mbggenerated
     */
    public void setPmpdcpvoldldrblasttti(Integer pmpdcpvoldldrblasttti) {
        this.pmpdcpvoldldrblasttti = pmpdcpvoldldrblasttti;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column temp.pmUeThpTimeUl
     *
     * @return the value of temp.pmUeThpTimeUl
     *
     * @mbggenerated
     */
    public Integer getPmuethptimeul() {
        return pmuethptimeul;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column temp.pmUeThpTimeUl
     *
     * @param pmuethptimeul the value for temp.pmUeThpTimeUl
     *
     * @mbggenerated
     */
    public void setPmuethptimeul(Integer pmuethptimeul) {
        this.pmuethptimeul = pmuethptimeul;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column temp.pmUeThpVolUl
     *
     * @return the value of temp.pmUeThpVolUl
     *
     * @mbggenerated
     */
    public Integer getPmuethpvolul() {
        return pmuethpvolul;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column temp.pmUeThpVolUl
     *
     * @param pmuethpvolul the value for temp.pmUeThpVolUl
     *
     * @mbggenerated
     */
    public void setPmuethpvolul(Integer pmuethpvolul) {
        this.pmuethpvolul = pmuethpvolul;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column temp.pmSessionTimeUe
     *
     * @return the value of temp.pmSessionTimeUe
     *
     * @mbggenerated
     */
    public Integer getPmsessiontimeue() {
        return pmsessiontimeue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column temp.pmSessionTimeUe
     *
     * @param pmsessiontimeue the value for temp.pmSessionTimeUe
     *
     * @mbggenerated
     */
    public void setPmsessiontimeue(Integer pmsessiontimeue) {
        this.pmsessiontimeue = pmsessiontimeue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column temp.pmSessionTimeDrb
     *
     * @return the value of temp.pmSessionTimeDrb
     *
     * @mbggenerated
     */
    public Integer getPmsessiontimedrb() {
        return pmsessiontimedrb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column temp.pmSessionTimeDrb
     *
     * @param pmsessiontimedrb the value for temp.pmSessionTimeDrb
     *
     * @mbggenerated
     */
    public void setPmsessiontimedrb(Integer pmsessiontimedrb) {
        this.pmsessiontimedrb = pmsessiontimedrb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column temp.pmActiveUeDlSum
     *
     * @return the value of temp.pmActiveUeDlSum
     *
     * @mbggenerated
     */
    public Integer getPmactiveuedlsum() {
        return pmactiveuedlsum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column temp.pmActiveUeDlSum
     *
     * @param pmactiveuedlsum the value for temp.pmActiveUeDlSum
     *
     * @mbggenerated
     */
    public void setPmactiveuedlsum(Integer pmactiveuedlsum) {
        this.pmactiveuedlsum = pmactiveuedlsum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column temp.pmActiveUeUlSum
     *
     * @return the value of temp.pmActiveUeUlSum
     *
     * @mbggenerated
     */
    public Integer getPmactiveueulsum() {
        return pmactiveueulsum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column temp.pmActiveUeUlSum
     *
     * @param pmactiveueulsum the value for temp.pmActiveUeUlSum
     *
     * @mbggenerated
     */
    public void setPmactiveueulsum(Integer pmactiveueulsum) {
        this.pmactiveueulsum = pmactiveueulsum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column temp.pmErabLevSamp
     *
     * @return the value of temp.pmErabLevSamp
     *
     * @mbggenerated
     */
    public Integer getPmerablevsamp() {
        return pmerablevsamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column temp.pmErabLevSamp
     *
     * @param pmerablevsamp the value for temp.pmErabLevSamp
     *
     * @mbggenerated
     */
    public void setPmerablevsamp(Integer pmerablevsamp) {
        this.pmerablevsamp = pmerablevsamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column temp.pmCellDowntimeAuto
     *
     * @return the value of temp.pmCellDowntimeAuto
     *
     * @mbggenerated
     */
    public Integer getPmcelldowntimeauto() {
        return pmcelldowntimeauto;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column temp.pmCellDowntimeAuto
     *
     * @param pmcelldowntimeauto the value for temp.pmCellDowntimeAuto
     *
     * @mbggenerated
     */
    public void setPmcelldowntimeauto(Integer pmcelldowntimeauto) {
        this.pmcelldowntimeauto = pmcelldowntimeauto;
    }
}