package com.ecom.entity.example;

import java.io.Serializable;

public class UserImportant implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_important.user_id
     *
     * @mbggenerated
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_important.important_tac
     *
     * @mbggenerated
     */
    private String importantTac;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_important.important_node
     *
     * @mbggenerated
     */
    private String importantNode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table user_important
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_important.user_id
     *
     * @return the value of user_important.user_id
     *
     * @mbggenerated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_important.user_id
     *
     * @param userId the value for user_important.user_id
     *
     * @mbggenerated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_important.important_tac
     *
     * @return the value of user_important.important_tac
     *
     * @mbggenerated
     */
    public String getImportantTac() {
        return importantTac;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_important.important_tac
     *
     * @param importantTac the value for user_important.important_tac
     *
     * @mbggenerated
     */
    public void setImportantTac(String importantTac) {
        this.importantTac = importantTac == null ? null : importantTac.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_important.important_node
     *
     * @return the value of user_important.important_node
     *
     * @mbggenerated
     */
    public String getImportantNode() {
        return importantNode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_important.important_node
     *
     * @param importantNode the value for user_important.important_node
     *
     * @mbggenerated
     */
    public void setImportantNode(String importantNode) {
        this.importantNode = importantNode == null ? null : importantNode.trim();
    }
}